version: '3.1'

services:
  redis-cache:
    image: redis:alpine
    container_name: redis-cache-container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-ecommerce

  mysql-db:
    image: mysql:8
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#      - ./mysql-db/user.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      - "3312:3306"
    networks:
      - spring-cloud-ecommerce

  auth-server:
    build:
      context: .
      dockerfile: ./server/auth-server/Dockerfile
    container_name: auth-server-container
    restart: always
    depends_on:
      - mysql-db
      - redis-cache
      - react-ui
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${AUTHENTICATION_SERVICE_PORT}
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    links:
      - mysql-db:mysql
    expose:
      - ${AUTHENTICATION_SERVICE_PORT}
    ports:
      - ${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}
    networks:
      - spring-cloud-ecommerce

  payment-service:
    build:
      context: .
      dockerfile: ./server/payment-service/Dockerfile
    container_name: payment-service-container
    restart: always
    depends_on:
      - redis-cache
      - react-ui
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${PAYMENT_SERVICE_PORT}
    expose:
      - ${PAYMENT_SERVICE_PORT}
    ports:
      - ${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}
    networks:
      - spring-cloud-ecommerce

  hystrix-dashboard:
    build:
      context: .
      dockerfile: ./server/hystrix-dashboard/Dockerfile
    container_name: hystrix-dashboard-container
    ports:
      - "5454:5454"
    networks:
      - spring-cloud-ecommerce

  react-ui:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: react-service-container
    stdin_open: true
    restart: always
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql-db
      - redis-cache
    networks:
      - spring-cloud-ecommerce

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build: ./server/eureka-server/.
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-ecommerce

  gateway-service:
    build:
      context: .
      dockerfile: ./server/product-service/Dockerfile
    container_name: gateway-service
    image: gateway-service
    environment:
      - JWT_TOKEN=${JWT_TOKEN}
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    ports:
      - "5353:5353"
    depends_on:
      - auth-server
    networks:
      - spring-cloud-ecommerce

  product-service:
    build:
      context: .
      dockerfile: ./server/product-service/Dockerfile
    container_name: product-service-container
    restart: always
    depends_on:
      - mysql-db
      - redis-cache
      - react-ui
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${PRODUCT_SERVICE_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis-cache
      - REDIS_PORT=${REDIS_PORT}
      - REACT_CLIENT_URL=${REACT_CLIENT_URL}
    links:
      - mysql-db:mysql
    expose:
      - ${PRODUCT_SERVICE_PORT}
    ports:
      - ${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}
    networks:
      - spring-cloud-ecommerce

networks:
  spring-cloud-ecommerce:
    external: true