version: '3.1'
services:
  product-service:
    container_name: product-service
    image: product-service
    build: ./product-service/.
    ports:
      - "3333:3333"
    depends_on:
      - postgresqldb
  user-service:
    container_name: user-service
    image: user-service
    build: ./user-service/.
    ports:
      - "3335:3335"
    depends_on:
      - mongodb
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build: ./eureka-server/.
    ports:
      - "1111:1111"
    depends_on:
      - product-service
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: furkanergun
    ports:
      - "27017:27017"
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=products