version: '3.1'
services:
  product-service:
    container_name: product-service
    image: product-service
    build: ./product-service/.
    ports:
      - "3333:3333"
    depends_on:
      - postgresqldb
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build: ./eureka-server/.
    ports:
      - "1111:1111"
    depends_on:
      - product-service
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=products