server:
  port: 5353

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: http://product-service:3333
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://user-service:3335
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true
    hostname: localhost
